# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install hatch==1.14.1
      - name: Run linters and tests
        run: hatch run dev:check

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential devscripts python3-yaml debhelper \
            python3-jinja2 python3-pytest dh-sequence-python3 \
            pybuild-plugin-pyproject python3-all python3-hatchling
      - name: Build .deb package
        run: debuild -uc -us -b
